### ISSUE TITLE
[BUG] - Bug name

### ISSUE THREAD

**Issue by WhofarTyd** [Investigamer/Proxyshop#88]
**Describe the bug**
I installed Proxyshop and checked for updates.  Colorshifted; Kaldheim Showcase;  Normal (MDFC Back); Normal (PW MDFC Back); Phyrexian Showcase, and Sketch Showcase

**To Reproduce**
1. I did restarted the program and tried checking for updates again.  I still got the same errors.  I deleted out all the templates and then went to download them all again in case there was an issue.  Still getting the errors on the same templates.
2. I also '....'
3. And also '...'

**Your system:**
 - Proxyshop or Python version: v1.13.2
 - Windows version:  Microsoft Windows 10 Pro
 - Photoshop version: 2024

**Screenshots**
![Untitled](https://github.com/Investigamer/Proxyshop/assets/169867137/8b8581ec-6e91-4967-a252-6447370ecdb3)

**Comment by Investigamer** [comment]
Can confirm the files are still up and will download on a fresh copy of Proxyshop v1.13.2, checked the templates you listed on two separate devices. I would just keep trying and make sure there's nothing going on with your system network related (turn off VPN if using one, disable virus blocker if using something temperamental like Norton or Mcaffee that could be blocking the download, etc).

**Comment by WhofarTyd** [comment]
I managed to get them installed.  Thanks for your help
