### ISSUE TITLE
[BUG] - Set Symbol Error

### ISSUE THREAD

**Issue by heirofseaandfire** [Investigamer/Proxyshop#92]
**Describe the bug**
Every card receives the set symbol for You Make the Cube.

**To Reproduce**
1. I made a card with Classic template using ascending release date.
2. I made a card with forced MH1 set symbol.
3. I made a card with art named with [5ED].

**Your system:**
 - Proxyshop or Python version: Proxyshop v1.13.2
 - Windows version: 10.0.19045 Build 19045
 - Photoshop version: 25.7.0 20240415.r.504 130b225  x64

**Screenshots**

**Comment by Investigamer** [comment]
Almost certainly caused by symbol API downtime around this period, not reproducible anymore.
